### ISSUE TITLE
How to stop automatic responses?

### ISSUE THREAD

**Issue by bookercodes** [arkcore/activator#6]
In my `/register` route handler, I send my own response to the user before calling `done()` which invokes the `activator.createActivate` middleware. 

``` javascript
app.post("/register", function(req, res, next) {
  var user = ...
  User.register(user, req.body.password, function(error, user) {
    req.flash("messages", "Thank you for registering. An email has been sent to you with an activation link: you will need to click that link in order to activate your account.");
    res.redirect("/");
    req.body._id = user.id; //set the _id for activator to pick up 
    next();
  });
}, activator.createActivate);
```

Because I already sent a response, `activator` results in the following error:

```
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:691:11)
    at ServerResponse.header (/home/booker/Documents/Code/authentication-template/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/home/booker/Documents/Code/authentication-template/node_modules/express/lib/response.js:163:12)
    at ServerResponse.json (/home/booker/Documents/Code/authentication-template/node_modules/express/lib/response.js:249:15)
    at ServerResponse.send (/home/booker/Documents/Code/authentication-template/node_modules/express/lib/response.js:151:21)
    at /home/booker/Documents/Code/authentication-template/node_modules/express-user-activator/lib/activator.js:335:22
    at createActivationPipeComplete (/home/booker/Documents/Code/authentication-template/node_modules/express-user-activator/lib/activator.js:102:5)
    at /home/booker/Documents/Code/authentication-template/node_modules/express-user-activator/lib/sendmail.js:90:7
    at /home/booker/Documents/Code/authentication-template/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/src/smtp-transport.js:86:20
    at /home/booker/Documents/Code/authentication-template/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:283:20
    at SMTPConnection._actionStream (/home/booker/Documents/Code/authentication-template/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:947:9)
    at SMTPConnection.<anonymous> (/home/booker/Documents/Code/authentication-template/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:575:14)
    at SMTPConnection._processResponse (/home/booker/Documents/Code/authentication-template/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:507:16)
    at SMTPConnection._onData (/home/booker/Documents/Code/authentication-template/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:357:10)
    at CleartextStream.EventEmitter.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:746:14)
```

It should be noted that the email _is_ sent successfully and this does _not_ interfere with anything but I do not want random exceptions poping up.

Is there a way to prevent activator from setting the response? I tried setting `createResponse` to an empty function but that results in another error:

```
TypeError: undefined is not a function
    at createActivationPipeComplete (/home/booker/Documents/Code/authentication-template/node_modules/express-user-activator/lib/activator.js:102:5)
    at /home/booker/Documents/Code/authentication-template/node_modules/express-user-activator/lib/sendmail.js:90:7
    at /home/booker/Documents/Code/authentication-template/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/src/smtp-transport.js:86:20
    at /home/booker/Documents/Code/authentication-template/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:283:20
    at SMTPConnection._actionStream (/home/booker/Documents/Code/authentication-template/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:947:9)
    at SMTPConnection.<anonymous> (/home/booker/Documents/Code/authentication-template/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:575:14)
    at SMTPConnection._processResponse (/home/booker/Documents/Code/authentication-template/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:507:16)
    at SMTPConnection._onData (/home/booker/Documents/Code/authentication-template/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:357:10)
    at CleartextStream.EventEmitter.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:746:14)
    at CleartextStream.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at _stream_readable.js:401:7
    at process._tickCallback (node.js:415:13)
```

**Comment by bookercodes** [comment]
I do not understand sorry. Can you please provide more details?

**Comment by AVVS** [comment]
use functions with `Next` postfix: https://github.com/arkcore/activator/blob/master/lib/activator.js#L446-L457

**Comment by bookercodes** [comment]
I used `activator.createActivateNext` instead of `activator.createActivate` and it worked. Thank you!

**Comment by bookercodes** [comment]
And thank you for your really quick responses!
